<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BlockQuote</name>
   <tag></tag>
   <elementGuidId>1e9f2547-3bed-402b-8ece-fac77fa7c370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ckeditor5-tabs-content&quot;]/div[1]/div[2]/div[1]/div/div[2]/div/button[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ckeditor5-tabs-content&quot;]/div[1]/div[2]/div[1]/div/div[2]/div/button[6]</value>
   </webElementProperties>
</WebElementEntity>
