<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LinkName</name>
   <tag></tag>
   <elementGuidId>b5a18e6f-de1f-42f2-bd28-243affed9c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ck-input-ecfe608e5f4afc5ff4e352e6f87b2b6f0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ck-input-ecfe608e5f4afc5ff4e352e6f87b2b6f0&quot;]</value>
   </webElementProperties>
</WebElementEntity>
