<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>A1</name>
   <tag></tag>
   <elementGuidId>70f64efd-9260-4684-af92-c625d5d20059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;udemy&quot;]/div[1]/div[2]/div[1]/div[4]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;udemy&quot;]/div[1]/div[2]/div[1]/div[4]/div[6]</value>
   </webElementProperties>
</WebElementEntity>
